version: '3.8'

services:
  watermarking-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./database/images:/app/database/images
      - ./results:/app/results
      - ./blockchain/database:/app/blockchain/database
      - ./configs/database:/app/configs/database
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  # Optional development service
  dev:
    build: .
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1